//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Columns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityLayer.Columns", typeof(Columns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivatedBy.
        /// </summary>
        internal static string ActivatedBy {
            get {
                return ResourceManager.GetString("ActivatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivationDate.
        /// </summary>
        internal static string ActivationDate {
            get {
                return ResourceManager.GetString("ActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressAr.
        /// </summary>
        internal static string AddressAr {
            get {
                return ResourceManager.GetString("AddressAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressEn.
        /// </summary>
        internal static string AddressEn {
            get {
                return ResourceManager.GetString("AddressEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArchiveDate.
        /// </summary>
        internal static string ArchiveDate {
            get {
                return ResourceManager.GetString("ArchiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArchivedBy.
        /// </summary>
        internal static string ArchivedBy {
            get {
                return ResourceManager.GetString("ArchivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchID.
        /// </summary>
        internal static string BranchID {
            get {
                return ResourceManager.GetString("BranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandID.
        /// </summary>
        internal static string BrandID {
            get {
                return ResourceManager.GetString("BrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanHaveOffers.
        /// </summary>
        internal static string CanHaveOffers {
            get {
                return ResourceManager.GetString("CanHaveOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryID.
        /// </summary>
        internal static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        internal static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosedBy.
        /// </summary>
        internal static string ClosedBy {
            get {
                return ResourceManager.GetString("ClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPerson.
        /// </summary>
        internal static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPersonEmail.
        /// </summary>
        internal static string ContactPersonEmail {
            get {
                return ResourceManager.GetString("ContactPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPersonMobile.
        /// </summary>
        internal static string ContactPersonMobile {
            get {
                return ResourceManager.GetString("ContactPersonMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreationDate.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyID.
        /// </summary>
        internal static string CurrencyID {
            get {
                return ResourceManager.GetString("CurrencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentBy.
        /// </summary>
        internal static string CurrentBy {
            get {
                return ResourceManager.GetString("CurrentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentDate.
        /// </summary>
        internal static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeactivatedBy.
        /// </summary>
        internal static string DeactivatedBy {
            get {
                return ResourceManager.GetString("DeactivatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeactivationDate.
        /// </summary>
        internal static string DeactivationDate {
            get {
                return ResourceManager.GetString("DeactivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionAr.
        /// </summary>
        internal static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionEn.
        /// </summary>
        internal static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountPercentage.
        /// </summary>
        internal static string DiscountPercentage {
            get {
                return ResourceManager.GetString("DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistrictAr.
        /// </summary>
        internal static string DistrictAr {
            get {
                return ResourceManager.GetString("DistrictAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistrictEn.
        /// </summary>
        internal static string DistrictEn {
            get {
                return ResourceManager.GetString("DistrictEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairID.
        /// </summary>
        internal static string FairID {
            get {
                return ResourceManager.GetString("FairID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HasChildren.
        /// </summary>
        internal static string HasChildren {
            get {
                return ResourceManager.GetString("HasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HasOffers.
        /// </summary>
        internal static string HasOffers {
            get {
                return ResourceManager.GetString("HasOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotLine.
        /// </summary>
        internal static string HotLine {
            get {
                return ResourceManager.GetString("HotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsArabic.
        /// </summary>
        internal static string IsArabic {
            get {
                return ResourceManager.GetString("IsArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsArchived.
        /// </summary>
        internal static string IsArchived {
            get {
                return ResourceManager.GetString("IsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBestDeal.
        /// </summary>
        internal static string IsBestDeal {
            get {
                return ResourceManager.GetString("IsBestDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsClosed.
        /// </summary>
        internal static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCurrent.
        /// </summary>
        internal static string IsCurrent {
            get {
                return ResourceManager.GetString("IsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFeaturedOffer.
        /// </summary>
        internal static string IsFeaturedOffer {
            get {
                return ResourceManager.GetString("IsFeaturedOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNew.
        /// </summary>
        internal static string IsNew {
            get {
                return ResourceManager.GetString("IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPackage.
        /// </summary>
        internal static string IsPackage {
            get {
                return ResourceManager.GetString("IsPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsProduct.
        /// </summary>
        internal static string IsProduct {
            get {
                return ResourceManager.GetString("IsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReplied.
        /// </summary>
        internal static string IsReplied {
            get {
                return ResourceManager.GetString("IsReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSale.
        /// </summary>
        internal static string IsSale {
            get {
                return ResourceManager.GetString("IsSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        internal static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationID.
        /// </summary>
        internal static string LocationID {
            get {
                return ResourceManager.GetString("LocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapZoom.
        /// </summary>
        internal static string MapZoom {
            get {
                return ResourceManager.GetString("MapZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile1.
        /// </summary>
        internal static string Mobile1 {
            get {
                return ResourceManager.GetString("Mobile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile2.
        /// </summary>
        internal static string Mobile2 {
            get {
                return ResourceManager.GetString("Mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile3.
        /// </summary>
        internal static string Mobile3 {
            get {
                return ResourceManager.GetString("Mobile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelAr.
        /// </summary>
        internal static string ModelAr {
            get {
                return ResourceManager.GetString("ModelAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelEn.
        /// </summary>
        internal static string ModelEn {
            get {
                return ResourceManager.GetString("ModelEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificationDate.
        /// </summary>
        internal static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedBy.
        /// </summary>
        internal static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameAr.
        /// </summary>
        internal static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameEn.
        /// </summary>
        internal static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameID.
        /// </summary>
        internal static string NameID {
            get {
                return ResourceManager.GetString("NameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPrice.
        /// </summary>
        internal static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferID.
        /// </summary>
        internal static string OfferID {
            get {
                return ResourceManager.GetString("OfferID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPrice.
        /// </summary>
        internal static string OldPrice {
            get {
                return ResourceManager.GetString("OldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageDescriptionAr.
        /// </summary>
        internal static string PackageDescriptionAr {
            get {
                return ResourceManager.GetString("PackageDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageDescriptionEn.
        /// </summary>
        internal static string PackageDescriptionEn {
            get {
                return ResourceManager.GetString("PackageDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentID.
        /// </summary>
        internal static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        internal static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        internal static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone3.
        /// </summary>
        internal static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollID.
        /// </summary>
        internal static string PollID {
            get {
                return ResourceManager.GetString("PollID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionID.
        /// </summary>
        internal static string PollOptionID {
            get {
                return ResourceManager.GetString("PollOptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateCount.
        /// </summary>
        internal static string RateCount {
            get {
                return ResourceManager.GetString("RateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateTotal.
        /// </summary>
        internal static string RateTotal {
            get {
                return ResourceManager.GetString("RateTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepliedBy.
        /// </summary>
        internal static string RepliedBy {
            get {
                return ResourceManager.GetString("RepliedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplyDate.
        /// </summary>
        internal static string ReplyDate {
            get {
                return ResourceManager.GetString("ReplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaleUpTo.
        /// </summary>
        internal static string SaleUpTo {
            get {
                return ResourceManager.GetString("SaleUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortDescriptionAr.
        /// </summary>
        internal static string ShortDescriptionAr {
            get {
                return ResourceManager.GetString("ShortDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortDescriptionEn.
        /// </summary>
        internal static string ShortDescriptionEn {
            get {
                return ResourceManager.GetString("ShortDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierID.
        /// </summary>
        internal static string SupplierID {
            get {
                return ResourceManager.GetString("SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextAr.
        /// </summary>
        internal static string TextAr {
            get {
                return ResourceManager.GetString("TextAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextEn.
        /// </summary>
        internal static string TextEn {
            get {
                return ResourceManager.GetString("TextEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleAr.
        /// </summary>
        internal static string TitleAr {
            get {
                return ResourceManager.GetString("TitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleEn.
        /// </summary>
        internal static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalVotes.
        /// </summary>
        internal static string TotalVotes {
            get {
                return ResourceManager.GetString("TotalVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitAr.
        /// </summary>
        internal static string UnitAr {
            get {
                return ResourceManager.GetString("UnitAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitEn.
        /// </summary>
        internal static string UnitEn {
            get {
                return ResourceManager.GetString("UnitEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        internal static string Votes {
            get {
                return ResourceManager.GetString("Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X_Coordination.
        /// </summary>
        internal static string XCoordination {
            get {
                return ResourceManager.GetString("XCoordination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y_Coordination.
        /// </summary>
        internal static string YCoordination {
            get {
                return ResourceManager.GetString("YCoordination", resourceCulture);
            }
        }
    }
}
