//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProceduresNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProceduresNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Resources.ProceduresNames", typeof(ProceduresNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandAdd.
        /// </summary>
        internal static string BrandAdd {
            get {
                return ResourceManager.GetString("BrandAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandDelete.
        /// </summary>
        internal static string BrandDelete {
            get {
                return ResourceManager.GetString("BrandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandSelectAll.
        /// </summary>
        internal static string BrandSelectAll {
            get {
                return ResourceManager.GetString("BrandSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandSelectByID.
        /// </summary>
        internal static string BrandSelectByID {
            get {
                return ResourceManager.GetString("BrandSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandUpdate.
        /// </summary>
        internal static string BrandUpdate {
            get {
                return ResourceManager.GetString("BrandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryAdd.
        /// </summary>
        internal static string CategoryAdd {
            get {
                return ResourceManager.GetString("CategoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryDelete.
        /// </summary>
        internal static string CategoryDelete {
            get {
                return ResourceManager.GetString("CategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySelectAll.
        /// </summary>
        internal static string CategorySelectAll {
            get {
                return ResourceManager.GetString("CategorySelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySelectBase.
        /// </summary>
        internal static string CategorySelectBase {
            get {
                return ResourceManager.GetString("CategorySelectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySelectByID.
        /// </summary>
        internal static string CategorySelectByID {
            get {
                return ResourceManager.GetString("CategorySelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySelectByOfferAbility.
        /// </summary>
        internal static string CategorySelectByOfferAbility {
            get {
                return ResourceManager.GetString("CategorySelectByOfferAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySelectByParentID.
        /// </summary>
        internal static string CategorySelectByParentID {
            get {
                return ResourceManager.GetString("CategorySelectByParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryUpdate.
        /// </summary>
        internal static string CategoryUpdate {
            get {
                return ResourceManager.GetString("CategoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsAdd.
        /// </summary>
        internal static string ContactUsAdd {
            get {
                return ResourceManager.GetString("ContactUsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsClose.
        /// </summary>
        internal static string ContactUsClose {
            get {
                return ResourceManager.GetString("ContactUsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsDelete.
        /// </summary>
        internal static string ContactUsDelete {
            get {
                return ResourceManager.GetString("ContactUsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsReply.
        /// </summary>
        internal static string ContactUsReply {
            get {
                return ResourceManager.GetString("ContactUsReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsSelectAll.
        /// </summary>
        internal static string ContactUsSelectAll {
            get {
                return ResourceManager.GetString("ContactUsSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsSelectByID.
        /// </summary>
        internal static string ContactUsSelectByID {
            get {
                return ResourceManager.GetString("ContactUsSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsSelectClosed.
        /// </summary>
        internal static string ContactUsSelectClosed {
            get {
                return ResourceManager.GetString("ContactUsSelectClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsSelectNew.
        /// </summary>
        internal static string ContactUsSelectNew {
            get {
                return ResourceManager.GetString("ContactUsSelectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUsSelectReplied.
        /// </summary>
        internal static string ContactUsSelectReplied {
            get {
                return ResourceManager.GetString("ContactUsSelectReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyAdd.
        /// </summary>
        internal static string CurrencyAdd {
            get {
                return ResourceManager.GetString("CurrencyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyDelete.
        /// </summary>
        internal static string CurrencyDelete {
            get {
                return ResourceManager.GetString("CurrencyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencySelectAll.
        /// </summary>
        internal static string CurrencySelectAll {
            get {
                return ResourceManager.GetString("CurrencySelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencySelectByID.
        /// </summary>
        internal static string CurrencySelectByID {
            get {
                return ResourceManager.GetString("CurrencySelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyUpdate.
        /// </summary>
        internal static string CurrencyUpdate {
            get {
                return ResourceManager.GetString("CurrencyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairActivate.
        /// </summary>
        internal static string FairActivate {
            get {
                return ResourceManager.GetString("FairActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairAdd.
        /// </summary>
        internal static string FairAdd {
            get {
                return ResourceManager.GetString("FairAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairCategoryAdd.
        /// </summary>
        internal static string FairCategoryAdd {
            get {
                return ResourceManager.GetString("FairCategoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairCategoryDelete.
        /// </summary>
        internal static string FairCategoryDelete {
            get {
                return ResourceManager.GetString("FairCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairDeactivate.
        /// </summary>
        internal static string FairDeactivate {
            get {
                return ResourceManager.GetString("FairDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairDelete.
        /// </summary>
        internal static string FairDelete {
            get {
                return ResourceManager.GetString("FairDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairLike.
        /// </summary>
        internal static string FairLike {
            get {
                return ResourceManager.GetString("FairLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairRate.
        /// </summary>
        internal static string FairRate {
            get {
                return ResourceManager.GetString("FairRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairSelectAll.
        /// </summary>
        internal static string FairSelectAll {
            get {
                return ResourceManager.GetString("FairSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairSelectByCatID.
        /// </summary>
        internal static string FairSelectByCatID {
            get {
                return ResourceManager.GetString("FairSelectByCatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairSelectByID.
        /// </summary>
        internal static string FairSelectByID {
            get {
                return ResourceManager.GetString("FairSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairSelectByLocationID.
        /// </summary>
        internal static string FairSelectByLocationID {
            get {
                return ResourceManager.GetString("FairSelectByLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairUpdate.
        /// </summary>
        internal static string FairUpdate {
            get {
                return ResourceManager.GetString("FairUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationAdd.
        /// </summary>
        internal static string LocationAdd {
            get {
                return ResourceManager.GetString("LocationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationDelete.
        /// </summary>
        internal static string LocationDelete {
            get {
                return ResourceManager.GetString("LocationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationSelectAll.
        /// </summary>
        internal static string LocationSelectAll {
            get {
                return ResourceManager.GetString("LocationSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationSelectByID.
        /// </summary>
        internal static string LocationSelectByID {
            get {
                return ResourceManager.GetString("LocationSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationUpdate.
        /// </summary>
        internal static string LocationUpdate {
            get {
                return ResourceManager.GetString("LocationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferActivate.
        /// </summary>
        internal static string OfferActivate {
            get {
                return ResourceManager.GetString("OfferActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferAdd.
        /// </summary>
        internal static string OfferAdd {
            get {
                return ResourceManager.GetString("OfferAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferBranchAdd.
        /// </summary>
        internal static string OfferBranchAdd {
            get {
                return ResourceManager.GetString("OfferBranchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferBranchDelete.
        /// </summary>
        internal static string OfferBranchDelete {
            get {
                return ResourceManager.GetString("OfferBranchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferDeactivate.
        /// </summary>
        internal static string OfferDeactivate {
            get {
                return ResourceManager.GetString("OfferDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferDelete.
        /// </summary>
        internal static string OfferDelete {
            get {
                return ResourceManager.GetString("OfferDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferLike.
        /// </summary>
        internal static string OfferLike {
            get {
                return ResourceManager.GetString("OfferLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferRate.
        /// </summary>
        internal static string OfferRate {
            get {
                return ResourceManager.GetString("OfferRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectAll.
        /// </summary>
        internal static string OfferSelectAll {
            get {
                return ResourceManager.GetString("OfferSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectBestDeal.
        /// </summary>
        internal static string OfferSelectBestDeal {
            get {
                return ResourceManager.GetString("OfferSelectBestDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectByBrandID.
        /// </summary>
        internal static string OfferSelectByBrandID {
            get {
                return ResourceManager.GetString("OfferSelectByBrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectByCatID.
        /// </summary>
        internal static string OfferSelectByCatID {
            get {
                return ResourceManager.GetString("OfferSelectByCatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectByCatIDBrandID.
        /// </summary>
        internal static string OfferSelectByCatIDBrandID {
            get {
                return ResourceManager.GetString("OfferSelectByCatIDBrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectByCatIDSuppID.
        /// </summary>
        internal static string OfferSelectByCatIDSuppID {
            get {
                return ResourceManager.GetString("OfferSelectByCatIDSuppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectByCatIDSuppIDBrandID.
        /// </summary>
        internal static string OfferSelectByCatIDSuppIDBrandID {
            get {
                return ResourceManager.GetString("OfferSelectByCatIDSuppIDBrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectByID.
        /// </summary>
        internal static string OfferSelectByID {
            get {
                return ResourceManager.GetString("OfferSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectBySuppID.
        /// </summary>
        internal static string OfferSelectBySuppID {
            get {
                return ResourceManager.GetString("OfferSelectBySuppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectBySuppIDBrandID.
        /// </summary>
        internal static string OfferSelectBySuppIDBrandID {
            get {
                return ResourceManager.GetString("OfferSelectBySuppIDBrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectFeatured.
        /// </summary>
        internal static string OfferSelectFeatured {
            get {
                return ResourceManager.GetString("OfferSelectFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectMostLiked.
        /// </summary>
        internal static string OfferSelectMostLiked {
            get {
                return ResourceManager.GetString("OfferSelectMostLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectMostViewed.
        /// </summary>
        internal static string OfferSelectMostViewed {
            get {
                return ResourceManager.GetString("OfferSelectMostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectNewPackage.
        /// </summary>
        internal static string OfferSelectNewPackage {
            get {
                return ResourceManager.GetString("OfferSelectNewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectNewProduct.
        /// </summary>
        internal static string OfferSelectNewProduct {
            get {
                return ResourceManager.GetString("OfferSelectNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectNewSale.
        /// </summary>
        internal static string OfferSelectNewSale {
            get {
                return ResourceManager.GetString("OfferSelectNewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSelectTopRated.
        /// </summary>
        internal static string OfferSelectTopRated {
            get {
                return ResourceManager.GetString("OfferSelectTopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSetBest.
        /// </summary>
        internal static string OfferSetBest {
            get {
                return ResourceManager.GetString("OfferSetBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSetFeatured.
        /// </summary>
        internal static string OfferSetFeatured {
            get {
                return ResourceManager.GetString("OfferSetFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSimpleSearch.
        /// </summary>
        internal static string OfferSimpleSearch {
            get {
                return ResourceManager.GetString("OfferSimpleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferSimpleSearchByCat.
        /// </summary>
        internal static string OfferSimpleSearchByCat {
            get {
                return ResourceManager.GetString("OfferSimpleSearchByCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferUpdate.
        /// </summary>
        internal static string OfferUpdate {
            get {
                return ResourceManager.GetString("OfferUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferView.
        /// </summary>
        internal static string OfferView {
            get {
                return ResourceManager.GetString("OfferView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollAdd.
        /// </summary>
        internal static string PollAdd {
            get {
                return ResourceManager.GetString("PollAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollArchive.
        /// </summary>
        internal static string PollArchive {
            get {
                return ResourceManager.GetString("PollArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollDelete.
        /// </summary>
        internal static string PollDelete {
            get {
                return ResourceManager.GetString("PollDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionAdd.
        /// </summary>
        internal static string PollOptionAdd {
            get {
                return ResourceManager.GetString("PollOptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionDelete.
        /// </summary>
        internal static string PollOptionDelete {
            get {
                return ResourceManager.GetString("PollOptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionDeleteByPollID.
        /// </summary>
        internal static string PollOptionDeleteByPollID {
            get {
                return ResourceManager.GetString("PollOptionDeleteByPollID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionSelectByID.
        /// </summary>
        internal static string PollOptionSelectByID {
            get {
                return ResourceManager.GetString("PollOptionSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionSelectByPollID.
        /// </summary>
        internal static string PollOptionSelectByPollID {
            get {
                return ResourceManager.GetString("PollOptionSelectByPollID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollOptionUpdate.
        /// </summary>
        internal static string PollOptionUpdate {
            get {
                return ResourceManager.GetString("PollOptionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollSelectAll.
        /// </summary>
        internal static string PollSelectAll {
            get {
                return ResourceManager.GetString("PollSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollSelectArchived.
        /// </summary>
        internal static string PollSelectArchived {
            get {
                return ResourceManager.GetString("PollSelectArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollSelectByID.
        /// </summary>
        internal static string PollSelectByID {
            get {
                return ResourceManager.GetString("PollSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollSelectCurrent.
        /// </summary>
        internal static string PollSelectCurrent {
            get {
                return ResourceManager.GetString("PollSelectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollSelectNew.
        /// </summary>
        internal static string PollSelectNew {
            get {
                return ResourceManager.GetString("PollSelectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollSetCurrent.
        /// </summary>
        internal static string PollSetCurrent {
            get {
                return ResourceManager.GetString("PollSetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollUpdate.
        /// </summary>
        internal static string PollUpdate {
            get {
                return ResourceManager.GetString("PollUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollVote.
        /// </summary>
        internal static string PollVote {
            get {
                return ResourceManager.GetString("PollVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierActivate.
        /// </summary>
        internal static string SupplierActivate {
            get {
                return ResourceManager.GetString("SupplierActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierAdd.
        /// </summary>
        internal static string SupplierAdd {
            get {
                return ResourceManager.GetString("SupplierAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierBranchAdd.
        /// </summary>
        internal static string SupplierBranchAdd {
            get {
                return ResourceManager.GetString("SupplierBranchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierBranchDelete.
        /// </summary>
        internal static string SupplierBranchDelete {
            get {
                return ResourceManager.GetString("SupplierBranchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierBranchSelectByID.
        /// </summary>
        internal static string SupplierBranchSelectByID {
            get {
                return ResourceManager.GetString("SupplierBranchSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierBranchSelectBySupplierID.
        /// </summary>
        internal static string SupplierBranchSelectBySupplierID {
            get {
                return ResourceManager.GetString("SupplierBranchSelectBySupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierBranchUpdate.
        /// </summary>
        internal static string SupplierBranchUpdate {
            get {
                return ResourceManager.GetString("SupplierBranchUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierDeactivate.
        /// </summary>
        internal static string SupplierDeactivate {
            get {
                return ResourceManager.GetString("SupplierDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierDelete.
        /// </summary>
        internal static string SupplierDelete {
            get {
                return ResourceManager.GetString("SupplierDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierSelectAll.
        /// </summary>
        internal static string SupplierSelectAll {
            get {
                return ResourceManager.GetString("SupplierSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierSelectByBranchID.
        /// </summary>
        internal static string SupplierSelectByBranchID {
            get {
                return ResourceManager.GetString("SupplierSelectByBranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierSelectByID.
        /// </summary>
        internal static string SupplierSelectByID {
            get {
                return ResourceManager.GetString("SupplierSelectByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierUpdate.
        /// </summary>
        internal static string SupplierUpdate {
            get {
                return ResourceManager.GetString("SupplierUpdate", resourceCulture);
            }
        }
    }
}
